[2025-02-02T20:45:36.307+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-02T20:45:36.327+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: batch_ingestion.generate_batch_data manual__2025-02-02T20:45:34.671656+00:00 [queued]>
[2025-02-02T20:45:36.338+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: batch_ingestion.generate_batch_data manual__2025-02-02T20:45:34.671656+00:00 [queued]>
[2025-02-02T20:45:36.340+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-02-02T20:45:36.355+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): generate_batch_data> on 2025-02-02 20:45:34.671656+00:00
[2025-02-02T20:45:36.370+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=234) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-02T20:45:36.367+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'batch_ingestion', 'generate_batch_data', 'manual__2025-02-02T20:45:34.671656+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/batch_ingestion.py', '--cfg-path', '/tmp/tmp1v9lmoqk']
[2025-02-02T20:45:36.372+0000] {standard_task_runner.py:72} INFO - Started process 236 to run task
[2025-02-02T20:45:36.373+0000] {standard_task_runner.py:105} INFO - Job 19: Subtask generate_batch_data
[2025-02-02T20:45:36.428+0000] {task_command.py:467} INFO - Running <TaskInstance: batch_ingestion.generate_batch_data manual__2025-02-02T20:45:34.671656+00:00 [running]> on host 89b2ca05427a
[2025-02-02T20:45:36.743+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='batch_ingestion' AIRFLOW_CTX_TASK_ID='generate_batch_data' AIRFLOW_CTX_EXECUTION_DATE='2025-02-02T20:45:34.671656+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-02T20:45:34.671656+00:00'
[2025-02-02T20:45:36.745+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-02T20:45:36.773+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-02T20:45:36.787+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-02T20:45:36.788+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=batch_ingestion, task_id=generate_batch_data, run_id=manual__2025-02-02T20:45:34.671656+00:00, execution_date=20250202T204534, start_date=20250202T204536, end_date=20250202T204536
[2025-02-02T20:45:36.831+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-02T20:45:36.863+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-02T20:45:36.866+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
